// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWindowSize():Promise<Array<number>>;

export function LoadOverlaySettings():Promise<string>;

export function MinimizeWindow():Promise<void>;

export function QuitApp():Promise<void>;

export function SaveOverlaySettings(arg1:string):Promise<boolean>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;
