// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWindowSize() {
  return window['go']['main']['App']['GetWindowSize']();
}

export function LoadOverlaySettings() {
  return window['go']['main']['App']['LoadOverlaySettings']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveOverlaySettings(arg1) {
  return window['go']['main']['App']['SaveOverlaySettings'](arg1);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}
